### ISSUE TITLE
Recent Wisdoms View

### ISSUE THREAD

**Issue by Crouchsnap** [sapphon/upwise#2]
I find myself scrolling to the bottom of the leaderboard to see if there are new wisdoms a lot, and would appreciate a view that shows recent activity. Bonus points for notifying me of new wisdoms if I'm logged in.

**Comment by sapphon** [comment]
This issue has been partially resolved by the addition of the /recentwisdom page to the app, pointed at by the 'Recent' link in the navbar.

I say 'partially' because, since I have no idea how I'd implement live notifications for logged-in users, I'm leaving those bonus points on the table for another day =)

**Comment by sapphon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User can click 'Recent' for a card list view of all wisdoms by time posted descending](https://trello.com/c/9AkVOI9q/111-user-can-click-recent-for-a-card-list-view-of-all-wisdoms-by-time-posted-descending)
